" System vimrc file for Vim on iOS

syntax on
set nocompatible
set number
set guioptions-=rm

set antialias
command Share :browse save
cmap <C-j> <Down>
cmap <C-k> <Up>

set guioptions=
set backspace=start,eol,indent
set laststatus=2

inoremap \ <ESC>
cnoremap \ <ESC>