" System vimrc file for Vim on iOS

syntax on
set nocompatible
set number
set guioptions-=rm

set antialias
command Share :browse save
command Mail :call SendAsMail()
cmap <C-S-j> <Down>
cmap <C-S-k> <Up>

set guioptions=
set backspace=start,eol,indent
set laststatus=2
set encoding=utf-8

function! SendAsMail()
:w
let t = expand("%:p")
    call confirm(t, "Activity")
endfunction